data:
  train_path: data/
  test_path: data/

model:
  model_name: bert-base-uncased
  model_class: CEModel
  trainner_class: Trainer
  metric_fnt: accuracy
  loss: CEloss
  optimizer: AdamW

train:
  seed: 42
  gpus: 1
  batch_size: 16
  max_epoch: 3
  dropout_rate: 0.1
  learning_rate: 5e-6
  max_length: 84
  optimizer_lr: 6e-6
  optimizer_eps: 1e-8